name: Build MeroShare CLI CI/CD

on:
 push:
    branches:
      - master
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        mkdir linux-amd64/
        GOOS=linux GOARCH=amd64 go build -v -o linux-amd64/ ./...
        find ./linux-amd64 -type f -exec mv {} {}-linux-amd64 \;
        mkdir windows-amd64/
        GOOS=windows GOARCH=amd64 go build -v -o windows-amd64/ ./...
        mkdir darwin-arm64/
        GOOS=darwin GOARCH=arm64 go build -v -o darwin-arm64/ ./...
        find ./darwin-arm64 -type f -exec mv {} {}-darwin-arm64 \;
        mkdir darwin-amd64/
        GOOS=darwin GOARCH=amd64 go build -v -o darwin-amd64/ ./...
        find ./darwin-amd64 -type f -exec mv {} {}-darwin-amd64 \;
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "linux-amd64/*,windows-amd64/*,darwin-arm64/*, darwin-amd64/*"
        token: ${{ secrets.GITHUB_TOKEN }}
